# Generated by Django 3.1.4 on 2020-12-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('sub_title', models.CharField(max_length=2048)),
                ('img', models.ImageField(upload_to='Projects_images/')),
            ],
        ),
    ]
