# Generated by Django 3.1.2 on 2020-12-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone_num', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('comment_text', models.TextField(verbose_name='Комментарий')),
            ],
        ),
    ]
