# Generated by Django 3.1.2 on 2020-12-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='collapse_sub_title_1',
            field=models.CharField(default='', max_length=1280),
        ),
        migrations.AddField(
            model_name='projects',
            name='collapse_sub_title_2',
            field=models.CharField(default='', max_length=1280),
        ),
        migrations.AddField(
            model_name='projects',
            name='collapse_sub_title_3',
            field=models.CharField(default='', max_length=1280),
        ),
        migrations.AddField(
            model_name='projects',
            name='collapse_sub_title_4',
            field=models.CharField(default='', max_length=1280),
        ),
        migrations.AddField(
            model_name='projects',
            name='collapse_title_1',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='projects',
            name='collapse_title_2',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='projects',
            name='collapse_title_3',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='projects',
            name='collapse_title_4',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='projects',
            name='sub_title_2',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_2',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='projects',
            name='sub_title',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
