# Generated by Django 3.1.2 on 2020-12-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_projects_img_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='img_2',
            field=models.ImageField(blank=True, default='', upload_to='Projects_images/'),
        ),
    ]
