# Generated by Django 3.1.2 on 2020-12-25 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_auto_20201224_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='collapse_sub_title_1',
            field=models.CharField(default='', max_length=1280),
        ),
        migrations.AddField(
            model_name='news',
            name='collapse_sub_title_2',
            field=models.CharField(default='', max_length=1280),
        ),
        migrations.AddField(
            model_name='news',
            name='collapse_sub_title_3',
            field=models.CharField(default='', max_length=1280),
        ),
        migrations.AddField(
            model_name='news',
            name='collapse_sub_title_4',
            field=models.CharField(default='', max_length=1280),
        ),
        migrations.AddField(
            model_name='news',
            name='collapse_title_1',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='news',
            name='collapse_title_2',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='news',
            name='collapse_title_3',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='news',
            name='collapse_title_4',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='news',
            name='img_2',
            field=models.ImageField(blank=True, default='', upload_to='News_images/'),
        ),
        migrations.AddField(
            model_name='news',
            name='sub_title_2',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='news',
            name='title_2',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='news',
            name='sub_title',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.CreateModel(
            name='Images_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='News_multiple_images/')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.news')),
            ],
        ),
    ]
