# Generated by Django 3.1.2 on 2020-12-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_auto_20201225_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='collapse_sub_title_1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='collapse_sub_title_2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='collapse_sub_title_3',
        ),
        migrations.RemoveField(
            model_name='news',
            name='collapse_sub_title_4',
        ),
        migrations.RemoveField(
            model_name='news',
            name='collapse_title_1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='collapse_title_2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='collapse_title_3',
        ),
        migrations.RemoveField(
            model_name='news',
            name='collapse_title_4',
        ),
        migrations.RemoveField(
            model_name='news',
            name='sub_title_2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_2',
        ),
        migrations.AddField(
            model_name='images_news',
            name='sub_title',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='images_news',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
