# Generated by Django 3.1.2 on 2020-12-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_auto_20201227_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images_news',
            name='image',
            field=models.ImageField(upload_to='News_multiple_images/'),
        ),
    ]
