# Generated by Django 3.1.2 on 2020-12-28 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='tags',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.tags'),
        ),
    ]
