# Generated by Django 3.1.2 on 2020-12-29 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_auto_20201229_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtags',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
