# Generated by Django 3.1.2 on 2020-12-29 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0017_images_products_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Images_Projects',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='sub_tag',
        ),
        migrations.AddField(
            model_name='products',
            name='sub_tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sites.subtags'),
        ),
    ]
