# Generated by Django 3.1.2 on 2020-12-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0018_auto_20201229_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сonsultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_phone', models.IntegerField(max_length=255)),
            ],
        ),
    ]
